"""
Incident SQLAlchemy model.
Stores emergency/incident reports generated by volunteers or staff.
"""
import datetime
from sqlalchemy import String, DateTime, Text, Enum as SAEnum, func
from sqlalchemy.orm import Mapped, mapped_column
from app.database import Base
import enum


class IncidentType(str, enum.Enum):
    MEDICAL = "medical"
    FIRE = "fire"
    LOST_CHILD = "lost_child"
    SECURITY = "security"
    SUSPICIOUS = "suspicious"
    OTHER = "other"


class IncidentStatus(str, enum.Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    RESOLVED = "resolved"


def _utcnow() -> datetime.datetime:
    return datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)


class Incident(Base):
    __tablename__ = "incidents"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    type: Mapped[str] = mapped_column(SAEnum(IncidentType), nullable=False)
    status: Mapped[str] = mapped_column(
        SAEnum(IncidentStatus), default=IncidentStatus.OPEN, nullable=False
    )
    location: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    reporter_role: Mapped[str] = mapped_column(String(50), nullable=False)
    ai_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime, default=_utcnow, nullable=False
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime,
        default=_utcnow,
        onupdate=_utcnow,
        nullable=False,
    )
